# Generated by Django 2.2.6 on 2019-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='eco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lux',
            field=models.IntegerField(default=0),
        ),
    ]
