# Generated by Django 2.2.6 on 2019-11-21 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fb_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data published'),
            preserve_default=False,
        ),
    ]
