# Generated by Django 2.2.6 on 2019-12-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_city_feedback_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
