# Generated by Django 2.2.6 on 2019-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_feedback_fb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_text',
            field=models.TextField(verbose_name='text of feedback to Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_info',
            field=models.TextField(verbose_name='Info about Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=50, verbose_name='name of Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_stars',
            field=models.IntegerField(default=0),
        ),
    ]
