# Generated by Django 2.2.6 on 2019-11-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191121_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_location',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
