# Generated by Django 2.2.6 on 2019-10-29 23:38

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_city_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_stars',
            field=models.IntegerField(validators=[index.models.validate_even]),
        ),
    ]
