# Generated by Django 2.2.6 on 2019-11-21 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191121_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50, verbose_name='name of Hotel')),
                ('hotel_info', models.TextField(verbose_name='Info about Hotel')),
                ('hotel_capacity', models.IntegerField(default=0)),
                ('hotel_stars', models.IntegerField(default=0)),
                ('hotel_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.City')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_text', models.TextField(verbose_name='text of feedback to Hotel')),
                ('fb_date', models.DateTimeField(verbose_name='data published')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
