# Generated by Django 2.2.6 on 2019-12-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'FeedBack'},
        ),
    ]
