# Generated by Django 2.2.6 on 2019-12-06 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191206_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fb_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data published'),
            preserve_default=False,
        ),
    ]
