# Generated by Django 2.2.6 on 2019-11-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('index', '0002_auto_20191122_2319'),
        # ('index', '0005_city_feedback_hotel'),
    ]

    operations = [
    ]
