# Generated by Django 2.2.6 on 2019-12-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_feedback_fb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='eco',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_pic1',
            field=models.ImageField(default='NULL', upload_to='hotel_pic1/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_pic2',
            field=models.ImageField(default='NULL', upload_to='hotel_pic2/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_pics',
            field=models.ImageField(default='NULL', upload_to='hotel_pics/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lux',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_capacity',
            field=models.IntegerField(default=10),
        ),
    ]
