# Generated by Django 2.2.6 on 2019-11-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesOfCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('frontImg', models.ImageField(default='NULL', upload_to='carImg/')),
                ('janImg', models.ImageField(default='NULL', upload_to='carImg/')),
                ('ishImg', models.ImageField(default='NULL', upload_to='carImg/')),
                ('madeDate', models.IntegerField(default=2000)),
                ('car_colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='white', max_length=50)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRent.CitiesOfCars')),
            ],
            options={
                'db_table': 'carModels',
            },
        ),
    ]
