# Generated by Django 2.2.6 on 2019-11-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRent', '0002_carmod_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='citiesofcars',
            name='city_Img',
            field=models.ImageField(default='NULL', upload_to='cityImg/'),
        ),
    ]
