# Generated by Django 2.2.6 on 2019-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRent', '0003_citiesofcars_city_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmod',
            name='car_colour',
            field=models.CharField(choices=[('White', 'White'), ('Wlack', 'Black'), ('Wellow', 'Yellow'), ('Gray', 'Gray')], default='White', max_length=50),
        ),
    ]
