# Generated by Django 2.2.6 on 2019-12-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRent', '0004_auto_20191207_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('start_rent', models.DateTimeField(blank=True, null=True, verbose_name='starting date')),
                ('end_rent', models.DateTimeField(blank=True, null=True, verbose_name='ending date')),
            ],
        ),
    ]
