# Generated by Django 2.2.6 on 2019-12-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRent', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmod',
            name='car_colour',
        ),
    ]
